/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewsRouteImport } from './routes/news'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminShiftsRouteImport } from './routes/_authenticated/admin/shifts'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminLettersRouteImport } from './routes/_authenticated/admin/letters'
import { Route as AuthenticatedAdminInformativoRouteImport } from './routes/_authenticated/admin/informativo'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin/employees'
import { Route as AuthenticatedAdminCheckinMessagesRouteImport } from './routes/_authenticated/admin/checkin-messages'
import { Route as AuthenticatedAdminCelebrationsRouteImport } from './routes/_authenticated/admin/celebrations'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminAlertsRouteImport } from './routes/_authenticated/admin/alerts'
import { Route as AuthenticatedAdminAccessMaintenanceRouteImport } from './routes/_authenticated/admin/access-maintenance'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin/access'
import { Route as AuthenticatedAdminEmployeesIdRouteImport } from './routes/_authenticated/admin/employees.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminShiftsRoute =
  AuthenticatedAdminShiftsRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLettersRoute =
  AuthenticatedAdminLettersRouteImport.update({
    id: '/letters',
    path: '/letters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInformativoRoute =
  AuthenticatedAdminInformativoRouteImport.update({
    id: '/informativo',
    path: '/informativo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCheckinMessagesRoute =
  AuthenticatedAdminCheckinMessagesRouteImport.update({
    id: '/checkin-messages',
    path: '/checkin-messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCelebrationsRoute =
  AuthenticatedAdminCelebrationsRouteImport.update({
    id: '/celebrations',
    path: '/celebrations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAlertsRoute =
  AuthenticatedAdminAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccessMaintenanceRoute =
  AuthenticatedAdminAccessMaintenanceRouteImport.update({
    id: '/access-maintenance',
    path: '/access-maintenance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesIdRoute =
  AuthenticatedAdminEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEmployeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/access-maintenance': typeof AuthenticatedAdminAccessMaintenanceRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/celebrations': typeof AuthenticatedAdminCelebrationsRoute
  '/admin/checkin-messages': typeof AuthenticatedAdminCheckinMessagesRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/admin/informativo': typeof AuthenticatedAdminInformativoRoute
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/access-maintenance': typeof AuthenticatedAdminAccessMaintenanceRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/celebrations': typeof AuthenticatedAdminCelebrationsRoute
  '/admin/checkin-messages': typeof AuthenticatedAdminCheckinMessagesRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/admin/informativo': typeof AuthenticatedAdminInformativoRoute
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/access-maintenance': typeof AuthenticatedAdminAccessMaintenanceRoute
  '/_authenticated/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/celebrations': typeof AuthenticatedAdminCelebrationsRoute
  '/_authenticated/admin/checkin-messages': typeof AuthenticatedAdminCheckinMessagesRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/_authenticated/admin/informativo': typeof AuthenticatedAdminInformativoRoute
  '/_authenticated/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/news'
    | '/settings'
    | '/admin'
    | '/admin/access'
    | '/admin/access-maintenance'
    | '/admin/alerts'
    | '/admin/attendance'
    | '/admin/celebrations'
    | '/admin/checkin-messages'
    | '/admin/employees'
    | '/admin/informativo'
    | '/admin/letters'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/'
    | '/admin/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/news'
    | '/settings'
    | '/admin/access'
    | '/admin/access-maintenance'
    | '/admin/alerts'
    | '/admin/attendance'
    | '/admin/celebrations'
    | '/admin/checkin-messages'
    | '/admin/employees'
    | '/admin/informativo'
    | '/admin/letters'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin'
    | '/admin/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/news'
    | '/settings'
    | '/_authenticated/admin'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/access-maintenance'
    | '/_authenticated/admin/alerts'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/celebrations'
    | '/_authenticated/admin/checkin-messages'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/informativo'
    | '/_authenticated/admin/letters'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/shifts'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NewsRoute: typeof NewsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shifts': {
      id: '/_authenticated/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AuthenticatedAdminShiftsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/letters': {
      id: '/_authenticated/admin/letters'
      path: '/letters'
      fullPath: '/admin/letters'
      preLoaderRoute: typeof AuthenticatedAdminLettersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/informativo': {
      id: '/_authenticated/admin/informativo'
      path: '/informativo'
      fullPath: '/admin/informativo'
      preLoaderRoute: typeof AuthenticatedAdminInformativoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/checkin-messages': {
      id: '/_authenticated/admin/checkin-messages'
      path: '/checkin-messages'
      fullPath: '/admin/checkin-messages'
      preLoaderRoute: typeof AuthenticatedAdminCheckinMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/celebrations': {
      id: '/_authenticated/admin/celebrations'
      path: '/celebrations'
      fullPath: '/admin/celebrations'
      preLoaderRoute: typeof AuthenticatedAdminCelebrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/alerts': {
      id: '/_authenticated/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AuthenticatedAdminAlertsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/access-maintenance': {
      id: '/_authenticated/admin/access-maintenance'
      path: '/access-maintenance'
      fullPath: '/admin/access-maintenance'
      preLoaderRoute: typeof AuthenticatedAdminAccessMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/employees/$id': {
      id: '/_authenticated/admin/employees/$id'
      path: '/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedAdminEmployeesRoute
    }
  }
}

interface AuthenticatedAdminEmployeesRouteChildren {
  AuthenticatedAdminEmployeesIdRoute: typeof AuthenticatedAdminEmployeesIdRoute
}

const AuthenticatedAdminEmployeesRouteChildren: AuthenticatedAdminEmployeesRouteChildren =
  {
    AuthenticatedAdminEmployeesIdRoute: AuthenticatedAdminEmployeesIdRoute,
  }

const AuthenticatedAdminEmployeesRouteWithChildren =
  AuthenticatedAdminEmployeesRoute._addFileChildren(
    AuthenticatedAdminEmployeesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAccessMaintenanceRoute: typeof AuthenticatedAdminAccessMaintenanceRoute
  AuthenticatedAdminAlertsRoute: typeof AuthenticatedAdminAlertsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminCelebrationsRoute: typeof AuthenticatedAdminCelebrationsRoute
  AuthenticatedAdminCheckinMessagesRoute: typeof AuthenticatedAdminCheckinMessagesRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRouteWithChildren
  AuthenticatedAdminInformativoRoute: typeof AuthenticatedAdminInformativoRoute
  AuthenticatedAdminLettersRoute: typeof AuthenticatedAdminLettersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShiftsRoute: typeof AuthenticatedAdminShiftsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
    AuthenticatedAdminAccessMaintenanceRoute:
      AuthenticatedAdminAccessMaintenanceRoute,
    AuthenticatedAdminAlertsRoute: AuthenticatedAdminAlertsRoute,
    AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
    AuthenticatedAdminCelebrationsRoute: AuthenticatedAdminCelebrationsRoute,
    AuthenticatedAdminCheckinMessagesRoute:
      AuthenticatedAdminCheckinMessagesRoute,
    AuthenticatedAdminEmployeesRoute:
      AuthenticatedAdminEmployeesRouteWithChildren,
    AuthenticatedAdminInformativoRoute: AuthenticatedAdminInformativoRoute,
    AuthenticatedAdminLettersRoute: AuthenticatedAdminLettersRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminShiftsRoute: AuthenticatedAdminShiftsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NewsRoute: NewsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
