-- GrupMar Time v10.1 — Santoral completo y módulo celebraciones
-- Idempotente para Supabase/Postgres.
-- Si la estructura real de BD usa otros nombres, mover estos datos a la tabla definitiva.

create table if not exists public.company_saints_calendar (
  id uuid primary key default gen_random_uuid(),
  date_mmdd text not null unique check (date_mmdd ~ '^[0-9]{2}-[0-9]{2}$'),
  names text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.company_saints_calendar is 'Santoral/onomástica por día MM-DD para avisos al fichar.';
comment on column public.company_saints_calendar.date_mmdd is 'Fecha recurrente en formato MM-DD.';
comment on column public.company_saints_calendar.names is 'Lista de nombres del santoral separados por coma.';

insert into public.company_saints_calendar (date_mmdd, names, active)
values
('01-01', 'Emanuel, Jesús, Manuel', true),
('01-02', 'Astrid, Basilio, Emma, Gregorio', true),
('01-03', 'Daniel, Florencio, Genova/Genoveva, Jennifer, Prisciliano', true),
('01-04', 'Eugenio', true),
('01-05', 'Amada, Emiliana, Simón, Simona', true),
('01-06', 'Adoración, Baltasar, Epifanía, Gaspar, Raymundo, Reyes', true),
('01-07', 'Amadeo, Aquiles, Luciano, Raimundo', true),
('01-08', 'Eladio, Maximino', true),
('01-09', 'Julián, Pedro', true),
('01-10', 'Alda, Aldo, Gonzalo, Hortensia, Marciano, Vilma', true),
('01-11', 'Alejandro, Guillermo, Higinia, Higinio, Hortensia, Modesto', true),
('01-12', 'Alfredo, Hilario, Tania, Tatiana', true),
('01-13', 'Milagros, Verónica', true),
('01-14', 'Félix, Gil', true),
('01-15', 'Marcelo, Mauro, Raquel', true),
('01-16', 'Odette, Oto, Priscila', true),
('01-17', 'Alba, Alfredo, Antonio, Mariana, Mariano', true),
('01-18', 'Beatriz, Florida, Mario, Pia', true),
('01-19', 'Mario, Sebastián, Vicente', true),
('01-20', 'Fabián', true),
('01-21', 'Vicente', true),
('01-22', 'Domingo, Emma, Gaudencio, Imanol', true),
('01-23', 'Alberta, Alberto, Armando, Ildefonso, María Paz, Xenia', true),
('01-24', 'Feliciano, Francisco, Paz', true),
('01-25', 'Elvira, Paula, Timoteo', true),
('01-26', 'Gonzalo, Paula, Tito', true),
('01-27', 'Ángela, Tomás, Valerio', true),
('01-28', 'Pedro, Tomas', true),
('01-29', 'Martina, Valeria, Valerio', true),
('01-30', 'Alejandro', true),
('01-31', 'Juan', true),
('02-01', 'Cecilio', true),
('02-02', 'Aída, Ayuda, Candelaria, Catalina, Felipe, Néstor, Purificación', true),
('02-03', 'Adelina, Blas, Oscar', true),
('02-04', 'Gilberto, Isidro, Juana, Verónica', true),
('02-05', 'Ágata, Águeda, Isaac', true),
('02-06', 'Amanda, Amando, Gonzalo, Silvano', true),
('02-07', 'Moisés, Ricardo', true),
('02-08', 'Elisanda, Jerónimo, Lucio', true),
('02-09', 'Apolonia, Donato, Reinaldo, Sabino', true),
('02-10', 'Amancio, Arnaldo, Arnau, Guillermo', true),
('02-11', 'Adolfo, Dante, Lourdes', true),
('02-12', 'Eulalia, Modesto', true),
('02-13', 'Benigno, Cristian', true),
('02-14', 'Dionisio, Odile, Valentín, Valentina', true),
('02-15', 'Faustino, Georgia, Georgina', true),
('02-16', 'Elías, Isaías, Jeremías, Samuel', true),
('02-17', 'Alexis, Constanza, Rómulo', true),
('02-18', 'Lucio, Simeón', true),
('02-19', 'Almudina, Álvaro, Conrado, Gabina, Gabino', true),
('02-20', 'Eleuterio', true),
('02-21', 'Irene, Pedro', true),
('02-22', 'Leonor, Margarita', true),
('02-23', 'Lázaro, Romance', true),
('02-24', 'Modesto', true),
('02-25', 'Cesáreo, Dióscoro', true),
('02-26', 'Néstor', true),
('02-27', 'Baldomero, Gabriel, Gabriela', true),
('02-28', 'Leandro, Román, Romano', true),
('03-01', 'Eudoxia, Eudoxio, Federico, Rosendo', true),
('03-02', 'Enrique, Enriqueta, Heraclio, Pablo', true),
('03-03', 'Medín, Rosendo', true),
('03-04', 'Arcadio, Casimiro, Eugenio, Francisca', true),
('03-05', 'Juan José', true),
('03-06', 'Humberto, Judith, Nina, Olegario', true),
('03-07', 'Clotilde, Felicidad', true),
('03-08', 'Juan', true),
('03-09', 'Cándido, Francisca', true),
('03-10', 'Andrés, Macario', true),
('03-11', 'Oria, Ramiro', true),
('03-12', 'Fina, Josefina, Maximiliano', true),
('03-13', 'Patricia, Ramiro, Rodrigo', true),
('03-14', 'Florentina, Jacobo, Matilde', true),
('03-15', 'César, Luis, Madrona, Raimundo', true),
('03-16', 'Abrahan, Clemente', true),
('03-17', 'Patricio', true),
('03-18', 'Narciso, Salvador', true),
('03-19', 'José, Josefa, Marcos', true),
('03-20', 'Alejandra, Claudia', true),
('03-21', 'Clemencia, Fabiola, Nicolás', true),
('03-22', 'Octaviano, Sergio', true),
('03-23', 'Fidel, José, Oriol, Victoriano', true),
('03-24', 'Delmiro, Edelmira, Edelmiro, Timolao', true),
('03-25', 'Abel, Anunciación, Encarnación, Gloria, Humberto, Maite, Rebeca', true),
('03-26', 'Braulio, Diego', true),
('03-27', 'Alejandro, Lilia, Ruperto', true),
('03-28', 'Esperanza, Gundelina', true),
('03-29', 'Jonas, Segundo', true),
('03-30', 'Quirino', true),
('03-31', 'Amós, Benjamín', true),
('04-01', 'Venancio', true),
('04-02', 'Francisco, Ofelia', true),
('04-03', 'Sixto', true),
('04-04', 'Isidoro, Platón', true),
('04-05', 'Emilia, Vicente', true),
('04-06', 'Celso, Diógenes', true),
('04-07', 'Donato, Juan', true),
('04-08', 'Amancio, Dionisio', true),
('04-09', 'Casilda, Eusequio, Hugo', true),
('04-10', 'Ezequiel', true),
('04-11', 'Estanislao, Gema, Oria', true),
('04-12', 'Andrés, Damián, Julio', true),
('04-13', 'Hermenegildo, Martín', true),
('04-14', 'Lamberto', true),
('04-15', 'Aníbal, Máximo', true),
('04-16', 'Bernadeta, Engracia', true),
('04-17', 'Anicéto, Rodolfo', true),
('04-18', 'Perfecto', true),
('04-19', 'Crescencio, León', true),
('04-20', 'Inés, Víctor', true),
('04-21', 'Anselmo', true),
('04-22', 'Alexander, Apeles, Teodoro', true),
('04-23', 'Adalberto, Jorge', true),
('04-24', 'Fidel, Honoria, Honorio, Leoncio', true),
('04-25', 'Antonieta, Antonio, Erminío, Herminío, Marcia, Marco', true),
('04-26', 'Basilio, Engracia, Isidoro, Marcelino', true),
('04-27', 'Montserrat, Zita', true),
('04-28', 'Amado, Pedro', true),
('04-29', 'Catalina, Karen, Katia, Teodora, Wilfredo', true),
('04-30', 'Amador, Jaime, Pía, Pío', true),
('05-01', 'Andeoro, Berta, Oroncio, Paciencia, Tamar, Tamara, Teodardo', true),
('05-02', 'Araceli, Atanasio, Exuperio, Germán, Mafalda, Vindemial, Zoé', true),
('05-03', 'Alejandro, Estela, Evencio, Felipe, Juvenal, Teódulo, Violeta', true),
('05-04', 'Florián, Froilán, Lidón, Paulino, Porfirio, Silvano', true),
('05-05', 'Adrián, Ángelica, Niceto, Silvano', true),
('05-06', 'Domingo, Evodio, Judith, Protógenes', true),
('05-07', 'Augusto, Flavio, Gisela', true),
('05-08', 'Acacio', true),
('05-09', 'Geroncio, Gregorio, Hermas', true),
('05-10', 'Gordiano, Job, Solange', true),
('05-11', 'Amparo, Anastasio, Estela, Eudaldo, Favio, Iluminado, Poncio', true),
('05-12', 'Aquileo, Domingo, Domitila, Flavia, Nerea, Nereo', true),
('05-13', 'Fátima, Imelda', true),
('05-14', 'Alba, Cora, Corona, Gemma, Henedina, Matías', true),
('05-15', 'Cecilio, Eufrasia, Indalecio, Isidro, Torcuato', true),
('05-16', 'Brenda, Honorato, Ubaldo', true),
('05-17', 'Eric, Erica, Pascual', true),
('05-18', 'Alejandra, Félix, Próspero', true),
('05-19', 'Celestina, Celestino, Crispín', true),
('05-20', 'Asterio, Baudilio, Orlando', true),
('05-21', 'Constantino, Giselle, Valente, Virginia', true),
('05-22', 'Emilio, Rita, Rosana', true),
('05-23', 'Desiderio, Eufebio, Humildad, Mercurial, Miguel', true),
('05-24', 'Auxiliadora, Ester, Providencia, Rocío, Susana', true),
('05-25', 'Sonia, Valentín, Valentina', true),
('05-26', 'Felipei, Zacarías', true),
('05-27', 'Carolina', true),
('05-28', 'Agustín, Bernardo, Emilio, Germán', true),
('05-29', 'Alejandro, Justo, Teodosia', true),
('05-30', 'Estela, Fernanda, Fernando, Hernán, Hernando, Lorena', true),
('05-31', 'Amelia, Avelina, Petronila, Visitación', true),
('06-01', 'Alta, Candelaria, Gracia, Graciano, Inigo, Jimena, Laura', true),
('06-02', 'Ausonia, Blandina, Edelmira, Erasmo, Marcelino', true),
('06-03', 'Cecilio, Clotilde, Davino, Kevin, Luciniano, Oliva', true),
('06-04', 'Emma, Noemí, Quirino, Ruth, Saturnina', true),
('06-05', 'Bonifacio, Doroteo, Eloisa, Igor, Marcia, Nicanor, Valeria', true),
('06-06', 'Amancio, Artemio, Cándida, Ismael, Norberto', true),
('06-07', 'Roberto', true),
('06-08', 'Giraldo', true),
('06-09', 'Blanca, Diana, Efraín, Feliciano, Primo', true),
('06-10', 'Amalia, Amelia, Asterio, Críspulo, Getulio, Máximo, Trinidad', true),
('06-11', 'Aléida, Benito, Bernabé', true),
('06-12', 'Cirilo, Nazario, Olimpo', true),
('06-13', 'Andoni, Antonia, Antonio, Joel', true),
('06-14', 'Digna, Eliseo, Félix', true),
('06-15', 'Benilde, Crescencia, Eutrópia, Landelino, Libia, Lidia, Vito', true),
('06-16', 'Alina, Aquilino, Aureliano, Ciro, Regina, Regis, Siro', true),
('06-17', 'Isauro, Ismael, Montano', true),
('06-18', 'Justo, Marceliano, Marina', true),
('06-19', 'Aurora', true),
('06-20', 'Elia, Macario, Silverio', true),
('06-21', 'Demetria, Gina, Koldo, Luis, Raul, Rodolfo, Terencio', true),
('06-22', 'Albano, Paulino', true),
('06-23', 'Agripina, Alicia, Apolo, Inmaculada, Walter', true),
('06-24', 'Iván, Ivana, Jean, Joan, Jon, Juan, Juana', true),
('06-25', 'Guillermo, Salomón', true),
('06-26', 'Alicia, Antelmo, Pelayo, Virgilio', true),
('06-27', 'Anecto, Ladislao, Sansón, Socorro, Zoilo', true),
('06-28', 'Marcela', true),
('06-29', 'Ciro, David, Pablo, Paola, Pedro, Siro', true),
('06-30', 'Leonila, Marcial', true),
('07-01', 'Aarón, Esther, Luz', true),
('07-02', 'Martiniano, Teobaldo, Teodorico, Vidal, Visitación', true),
('07-03', 'Amable, Enrique, Heliodoro, Jacinto, Tomás', true),
('07-04', 'Berta, Elizabeth, Inocencio, Isabel, Laureano', true),
('07-05', 'Filomena, Filomeno, Zoa', true),
('07-06', 'Dominica, Isaías, Rómulo', true),
('07-07', 'Fermín, Germano, Odón, Peregrino, Roberto', true),
('07-08', 'Adrián, Edgar, Marina, Priscila', true),
('07-09', 'Milagros, Verónica', true),
('07-10', 'Cristóbal, Honorato, Silvano', true),
('07-11', 'Abundio, Benito, Olga, Sabino', true),
('07-12', 'Oliverio, Paulina', true),
('07-13', 'Eugenio, Joel, Sara', true),
('07-14', 'Camila, Camilo, Vladimiro', true),
('07-15', 'Carmela, Carmelo, Fausto, Hilaria, Hilario', true),
('07-16', 'Carmen, Generosa, Marcelina', true),
('07-17', 'Elías', true),
('07-18', 'Emiliano, Federico, Luz', true),
('07-19', 'Aurea, Aureo', true),
('07-20', 'Elías, Elisa', true),
('07-21', 'Angelina, Angelines, Daniel, Julia, Lorenza', true),
('07-22', 'Magdalena, Primitiva, Teófila, Zaida, Zoraida', true),
('07-23', 'Boris, Brigida, Teresa', true),
('07-24', 'Cristina', true),
('07-25', 'Jaime, Santiago', true),
('07-26', 'Ana, Joaquín', true),
('07-27', 'Cucufate, Natalia', true),
('07-28', 'Celso', true),
('07-29', 'Marta, Olavo', true),
('07-30', 'Abdón', true),
('07-31', 'Ignacio', true),
('08-01', 'Alfonso, Dalmau', true),
('08-02', 'Angeles, Eusebio', true),
('08-03', 'Gustavo, Lídia', true),
('08-04', 'Juan María', true),
('08-05', 'Africa, Blanca, Nieves', true),
('08-06', 'Salvador', true),
('08-07', 'Cayetano', true),
('08-08', 'Domingo', true),
('08-09', 'Edith', true),
('08-10', 'Lorenzo', true),
('08-11', 'Clara, Filomena, Susana', true),
('08-12', 'Herculano', true),
('08-13', 'Aurora, Hipólito', true),
('08-14', 'Atanasia', true),
('08-15', 'Asunción, Estrella, José, María, Paloma', true),
('08-16', 'Roque', true),
('08-17', 'Isaac, Jacinto', true),
('08-18', 'Elena', true),
('08-19', 'Magín', true),
('08-20', 'Bernardo', true),
('08-21', 'Sidonio', true),
('08-22', 'Reina', true),
('08-23', 'Rosa', true),
('08-24', 'Bartolomé', true),
('08-25', 'Ginés', true),
('08-26', 'Ceferino', true),
('08-27', 'Mónica', true),
('08-28', 'Agustín', true),
('08-29', 'Sabina', true),
('08-30', 'Gaudencia', true),
('08-31', 'Raimón, Ramón', true),
('09-01', 'Arturo, Egidio, Gil', true),
('09-02', 'Antolín, Raquel', true),
('09-03', 'Dorotea', true),
('09-04', 'Moisés, Rosalía', true),
('09-05', 'Eudosio', true),
('09-06', 'Eva, Fausto', true),
('09-07', 'Regina', true),
('09-08', 'Adela, Meritxell, Nuria', true),
('09-09', 'Claustro, Felicia', true),
('09-10', 'Nicolás', true),
('09-11', 'Patiens', true),
('09-12', 'Dulce, María', true),
('09-13', 'Juan', true),
('09-14', 'Exaltación', true),
('09-15', 'Aurora, Dolores', true),
('09-16', 'Rogelio', true),
('09-17', 'Ariadna, Columba, Roberto', true),
('09-18', 'Sofía', true),
('09-19', 'Nilo', true),
('09-20', 'Eustaquio', true),
('09-21', 'Mateo, Mauricio', true),
('09-22', 'Digna, Inocencio', true),
('09-23', 'Lina, Lino, Tecla', true),
('09-24', 'Gerardo, Mercedes', true),
('09-25', 'Dalmacio', true),
('09-26', 'Cosme, Damián', true),
('09-27', 'Florentino, Vicente', true),
('09-28', 'Wenceslao', true),
('09-29', 'Gabriel, Miguel, Rafael', true),
('09-30', 'Jerónimo', true),
('10-01', 'Teresa', true),
('10-02', 'Angeles Custodios', true),
('10-03', 'Cándido, Francisco', true),
('10-04', 'Francisco', true),
('10-05', 'Gala, Plácido', true),
('10-06', 'Bruno', true),
('10-07', 'Rosario', true),
('10-08', 'Salud, Thaís', true),
('10-09', 'Abrahan, Dionisio', true),
('10-10', 'Tomás', true),
('10-11', 'Begona', true),
('10-12', 'Pilar, Serafín', true),
('10-13', 'Eduardo', true),
('10-14', 'Calixto', true),
('10-15', 'Teresa', true),
('10-16', 'Margarita, María', true),
('10-17', 'Ignacio', true),
('10-18', 'Lucas', true),
('10-19', 'Laura', true),
('10-20', 'Academia, Irene', true),
('10-21', 'Griselda, Ursula', true),
('10-22', 'Salomé', true),
('10-23', 'Servando', true),
('10-24', 'Antonio', true),
('10-25', 'Bernardo', true),
('10-26', 'Evaristo', true),
('10-27', 'Capitolina', true),
('10-28', 'Judas, Simón, Tadeo', true),
('10-29', 'Narciso', true),
('10-30', 'Bienvenida, Claudio', true),
('10-31', 'Quintin', true),
('11-01', 'Benigno, Penélope', true),
('11-02', 'Gorka, Jorge', true),
('11-03', 'Ermengol, Silvia', true),
('11-04', 'Carlos, Carlota, Carolina', true),
('11-05', 'Elisabet, Isabel, Zacarías', true),
('11-06', 'Leonardo', true),
('11-07', 'Carina, Ernesto', true),
('11-08', 'Severiano', true),
('11-09', 'Teodoro', true),
('11-10', 'Almudena, León', true),
('11-11', 'Martín', true),
('11-12', 'Aurelio', true),
('11-13', 'Diego, Leandro', true),
('11-14', 'Clemente, Teodoto', true),
('11-15', 'Alberto, Leopoldo', true),
('11-16', 'Edmundo, Margarita', true),
('11-17', 'Gertrudis, Hilda, Isabel, Victoria', true),
('11-18', 'Aurelio', true),
('11-19', 'Crispino, Fausto', true),
('11-20', 'Félix, Lucrecia, Ocatavio', true),
('11-21', 'Demetrio, Fructuoso, Piedad', true),
('11-22', 'Cecilia', true),
('11-23', 'Clemente', true),
('11-24', 'Flora', true),
('11-25', 'Erasmo', true),
('11-26', 'Juan', true),
('11-27', 'Auxilio', true),
('11-28', 'Rufo', true),
('11-29', 'Saturnino', true),
('11-30', 'Andrés', true),
('12-01', 'Adelaida, Eloy, Hugo', true),
('12-02', 'Elisa, Elsa', true),
('12-03', 'Francisco Javier, María', true),
('12-04', 'Bárbara', true),
('12-05', 'Crispina', true),
('12-06', 'Nicolás', true),
('12-07', 'Ambrosio', true),
('12-08', 'Concepción, Inmaculada, Pura', true),
('12-09', 'Juan', true),
('12-10', 'Eulalia', true),
('12-11', 'Dámaso', true),
('12-12', 'Chantal, Guadalupe', true),
('12-13', 'Lucía', true),
('12-14', 'Juan, Nicasio, Pompeyo', true),
('12-15', 'Cristina, Fortunato', true),
('12-16', 'Albina', true),
('12-17', 'Lázaro, Yolanda', true),
('12-18', 'Esperanza, Macarena', true),
('12-19', 'Darío', true),
('12-20', 'Ptolomeo', true),
('12-21', 'Pedro', true),
('12-22', 'Floro', true),
('12-23', 'Juan', true),
('12-24', 'Delfín, Társila', true),
('12-25', 'Belén, Eugenia, Natividad', true),
('12-26', 'Esteban', true),
('12-27', 'Teófanos', true),
('12-28', 'Abel', true),
('12-29', 'Davíd', true),
('12-30', 'Raúl', true),
('12-31', 'Silvestre', true)
on conflict (date_mmdd)
do update set
  names = excluded.names,
  active = excluded.active,
  updated_at = now();

alter table public.company_saints_calendar enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'company_saints_calendar'
      and policyname = 'company_saints_calendar_read_authenticated'
  ) then
    create policy company_saints_calendar_read_authenticated
    on public.company_saints_calendar
    for select
    to authenticated
    using (active = true);
  end if;
end $$;


create table if not exists public.company_holidays_calendar (
  id uuid primary key default gen_random_uuid(),
  date_mmdd text not null,
  name text not null,
  scope text not null default 'Empresa',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(date_mmdd, name, scope)
);

create table if not exists public.employee_celebrations (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid null,
  full_name text not null,
  email text null,
  birthday_mmdd text null check (birthday_mmdd is null or birthday_mmdd ~ '^[0-9]{2}-[0-9]{2}$'),
  department text null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.company_holidays_calendar enable row level security;
alter table public.employee_celebrations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'company_holidays_calendar'
      and policyname = 'company_holidays_calendar_read_authenticated'
  ) then
    create policy company_holidays_calendar_read_authenticated
    on public.company_holidays_calendar
    for select
    to authenticated
    using (active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'employee_celebrations'
      and policyname = 'employee_celebrations_read_authenticated'
  ) then
    create policy employee_celebrations_read_authenticated
    on public.employee_celebrations
    for select
    to authenticated
    using (active = true);
  end if;
end $$;
